name: Test Suite
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '35 19 10 * *'  # 10th of the month at 7:35pm UTC
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-test:
    uses: Elmeric/my-gha-workflows/.github/workflows/poetry-build-and-test.yml@v1
    secrets: inherit
    with:
      matrix-os-version: "[ 'ubuntu-latest' ]"
      matrix-python-version: "[ '3.7' ]"
#      matrix-os-version: "[ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]"
#      matrix-python-version: "[ '3.7', '3.8', '3.9', '3.10', '3.11' ]"
      poetry-version: "1.2.2"
